core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name="index"),
    path('settings', views.settings, name="settings"),
    path('signup', views.signup, name="signup"),
    path('signin', views.signin, name="signin"),
    path('logout', views.logout, name="logout"),

    path('user/<int:pk>/', views.person_update_view, name='update_profile'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'), # AJAX
]

social_book/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

# Create your models here.

class Country(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name

class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id_user = models.IntegerField()
    bio = models.TextField(blank=True)
    profileimg = models.ImageField(upload_to='profile_images', default='blank-profile-picture.png')
    location = models.CharField(max_length=50, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self) -> str:
        return str(self.pk) + " " + self.user.username

core/forms.py
from django import forms

from .models import City, Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['location', 'country', 'city']

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['city'].queryset = City.objects.none()

            if 'country' in self.data:
                try:
                    country_id = int(self.data.get('country'))
                    self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty City queryset
            elif self.instance.pk:
                self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

core/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, auth
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from core.forms import ProfileForm

from .models import City, Profile

# Create your views here.

@login_required(login_url='/signin')
def index(request):
    current_user = Profile.objects.get(user=request.user)
    print(current_user)
    return render(request, 'index.html', {'user':current_user})

@login_required(login_url='/signin')
def settings(request):
    user_profile = Profile.objects.get(user=request.user)

    if request.method == 'POST':

        if request.FILES.get('image') == None:
            image = user_profile.profileimg
            bio = request.POST['bio']
            location = request.POST['location']

            user_profile.profileimg = image
            user_profile.bio = bio
            user_profile.location = location
            user_profile.save()
        if request.FILES.get('image'):
            image = request.FILES.get('image')
            bio = request.POST['bio']
            location = request.POST['location']

            user_profile.profileimg = image
            user_profile.bio = bio
            user_profile.location = location
            user_profile.save()
        return redirect('/settings')


    return render(request, 'setting.html', {'user_profile':user_profile})

def signup(request):

    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        # user_model = User.objects.filter(username=username)
        # print(user_model[0].id)
        # return render(request, 'signup.html')

        if password == password2:
            if User.objects.filter(email=email).exists():
                messages.info(request, 'Email already exists.')
                return redirect('/signup')
            elif User.objects.filter(username=username).exists():
                messages.info(request, 'Username is already taken.')
                return redirect('/signup')
            else:
                user = User.objects.create_user(username=username, email=email, password=password)
                user.save()

                # login user and redirect to settings page
                user_login = auth.authenticate(username=username, password=password)
                auth.login(request, user_login)

                # create a profile for new user
                user_model = User.objects.get(username=username)
                new_profile = Profile.objects.create(user=user_model, id_user=user_model.id)
                print(user_model)
                new_profile.save()
                return redirect('/settings')
        else:
            messages.info(request, 'Password didn\'t match.')
            return redirect('/signup')

    else:
        return render(request, 'signup.html')

def signin(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Credentials Invalid')
            return redirect('/signin')

    else:
        return render(request, 'signin.html')

@login_required(login_url='/signin')
def logout(request):
    auth.logout(request)
    return redirect('/signin')



#======== EXTRA CODE FOR PRACTICE ========#
def person_update_view(request, pk):
    person = get_object_or_404(Profile, pk=pk)
    form = ProfileForm(instance=person)
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            messages.info(request, 'Profile updated successfully')
            return redirect('core:update_profile', pk=pk)
    return render(request, 'update_profile.html', {'form': form})

# AJAX
def load_cities(request):
    country_id = request.GET.get('country_id')
    cities = City.objects.filter(country_id=country_id).all()
    return render(request, 'city_dropdown_list_options.html', {'cities': cities})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)

templates/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

templates/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
	<title>Profile - {{username}}</title>
   <!-- <link rel="icon" href="images/fav.png" type="image/png" sizes="16x16"> -->
    
    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>
<body>
<!--<div class="se-pre-con"></div>-->
<div class="theme-layout">
	
	</div>
	
	<section>
			<div class="feature-photo">
				<figure><img src="{% static 'images/resources/timeline-1.jpg' %}" alt=""></figure>
				<form>
					<div class="add-btn">
					<span style="color: white; font-size: 27px; margin-right: 520px;"><b><u><a href="/">Home</a></u></b></span>
					<span style="color: white; font-size: 27px;"><b>11 Post</b></span>
					<span style="color: white; font-size: 27px;"><b>1.7m followers</b></span>
					<span style="color: white; font-size: 27px;"><b>3.5k following</b></span>
					<a href="" title="" data-ripple=""><button style="background-color: #ffc0cb; border: #ffc0cb;">Follow</button></a>
					
					</div>
				</form>

				<!-- <form class="edit-phto">
					<i class="fa fa-camera-retro"></i>
					<label class="fileContainer">
						Upload Cover Photo
					<input type="file"/>
					</label>
				</form> -->
				<div class="container-fluid">
					<div class="row merged">
						<div class="col-lg-2 col-sm-3">
							<div class="user-avatar">
								<figure>
									<img src="https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png" style="height: 250px; width: 100%;" alt="">
									<form class="edit-phto">
										<i class="fa fa-camera-retro"></i>
										<label class="fileContainer">
											<a href="#account-settings">Upload Profile Photo</a>
										</label>
									</form>
								</figure>
							</div>
						</div>
						<div class="col-lg-10 col-sm-9">
							<div class="timeline-info">
								<ul>
									<li class="admin-name">
									  <h5 style="color: black;white-space: nowrap; width: 110px; font-size: 27px;"><b>@username</b><!--<i class="fa fa-check-circle" style="color: #48dbfb;" aria-hidden="true"></i>--></h5>
									  <!--<span>Group Admin</span>-->
									</li>
									<!--<li>
										<a class="" href="javascript:void(0)" title="" data-ripple="">Go live!</a>
										<a class="" href="javascript:void(0)" title="" data-ripple="">Music</a>
										<a class="" href="emporium/index-3.html" title="" data-ripple="">Emporium</a>
										<a class="" href="fitness/index.html" title="" data-ripple="">Health Inspection</a>
										<a class="" href="settings/account-setting.html" title="" data-ripple="">Settings</a>
										<a class="" href="javascript:void(0)" title="" data-ripple="">Upload</a>
										<a class="" href="time-line.html" title="" data-ripple="">time line</a>
										<a class="" href="timeline-photos.html" title="" data-ripple="">Photos</a>
										<a class="" href="timeline-videos.html" title="" data-ripple="">Videos</a>
										<a class="" href="timeline-friends.html" title="" data-ripple="">Friends</a>
										<a class="" href="timeline-groups.html" title="" data-ripple="">Groups</a>
										<a class="" href="about.html" title="" data-ripple="">about</a>
										<a class="" href="#" title="" data-ripple="">more</a>

									</li>-->
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section><!-- top area -->
		<section>
			<div class="bio">
				Bio goes here...
			</div>
		</section>
		
	<section>
		<div class="gap gray-bg">
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="row" id="page-contents">
							<div class="col-lg-3">
								<aside class="sidebar static">
									
									
									
								</aside>
							</div><!-- sidebar -->
							









							<div class="col-lg-6">
								<div class="central-meta">
									<ul class="photos">
					
										<li>
											<a class="strip" href="https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png" title="" data-strip-group="mygroup" data-strip-group-options="loop: false">
												<img src="https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png" style="height: 250px; width: 300px;" alt=""></a>
										</li>

										<li>
											<a class="strip" href="https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png" title="" data-strip-group="mygroup" data-strip-group-options="loop: false">
												<img src="https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png" style="height: 250px; width: 300px;" alt=""></a>
										</li>

										<li>
											<a class="strip" href="https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png" title="" data-strip-group="mygroup" data-strip-group-options="loop: false">
												<img src="https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png" style="height: 250px; width: 300px;" alt=""></a>
										</li>
										
										
									</ul>
									<!--<div class="lodmore"><button class="btn-view btn-load-more"></button></div>-->
								</div><!-- photos -->
							</div><!-- centerl meta -->
							<div class="col-lg-3">
								<aside class="sidebar static">
									
								</aside>
							</div><!-- sidebar -->
						</div>	
					</div>
				</div>
			</div>
		</div>	
	</section>

	
	
	<script data-cfasync="false" src="{% static '../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js' %}"></script><script src="js/main.min.js"></script>
	<script src="{% static 'js/script.js' %}"></script>

</body>	


</html>

templates/signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="{% static 'assets/images/favicon.png' %}"
      rel="icon"
      type="image/png"
    />
    <title>sign in</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}" />
  </head>

  <body class="bg-gray-100">
    <div id="wrapper" class="flex flex-col justify-between h-screen">
      <!-- header-->
      <div class="bg-white py-4 shadow dark:bg-gray-800">
        <div class="max-w-6xl mx-auto">
          <div class="flex items-center lg:justify-between justify-around">
            <a href="trending.html">
              <b><h1 style="font-size: 1.5rem">Social Book</h1></b>
            </a>

            <div
              class="capitalize flex font-semibold hidden lg:block my-2 space-x-3 text-center text-sm"
            >
              <a
                href="{% url 'core:signup' %}"
                class="bg-pink-500 pink-500 px-6 py-3 rounded-md shadow text-white"
                >Register</a
              >
            </div>
          </div>
        </div>
      </div>

      <!-- Content-->
      <div>
        <div
          class="lg:p-12 max-w-md max-w-xl lg:my-0 my-12 mx-auto p-6 space-y-"
        >
          <h1 class="lg:text-3xl text-xl font-semibold mb-6">Log in</h1>

          <div>
            <style>
              h5 {
                color: salmon;
              }
            </style>

            {% for message in messages %}
            <h5>{{message}}</h5>
            {% endfor %}
          </div>

          <form action="" method="POST">
            {% csrf_token %}

            <input
              type="text"
              name="username"
              placeholder="Username"
              class="bg-gray-200 mb-2 shadow-none dark:bg-gray-800"
              style="border: 1px solid #d3d5d8 !important"
            />
            <input
              type="password"
              name="password"
              placeholder="Password"
              class="bg-gray-200 mb-2 shadow-none dark:bg-gray-800"
              style="border: 1px solid #d3d5d8 !important"
            />

            <button
              type="submit"
              class="bg-gradient-to-br from-pink-500 py-3 rounded-md text-white text-xl to-red-400 w-full"
            >
              Login
            </button>
            <div class="text-center mt-5 space-x-2">
              <p class="text-base">
                Not registered?
                <a href="{% url 'core:signup' %}" class="">
                  Create a account
                </a>
              </p>
            </div>
          </form>
        </div>
      </div>

      <!-- Footer -->

      <div class="lg:mb-5 py-3 uk-link-reset">
        <div
          class="flex flex-col items-center justify-between lg:flex-row max-w-6xl mx-auto lg:space-y-0 space-y-3"
        >
          <div class="flex space-x-2 text-gray-700 uppercase">
            <a href="#"> About</a>
            <a href="#"> Help</a>
            <a href="#"> Terms</a>
            <a href="#"> Privacy</a>
          </div>
          <p class="capitalize">© copyright 2020 by socol</p>
        </div>
      </div>
    </div>

    <!--<script>

        (function (window, document, undefined) {
            'use strict';
            if (!('localStorage' in window)) return;
            var nightMode = localStorage.getItem('gmtNightMode');
            if (nightMode) {
                document.documentElement.className += ' dark';
            }
        })(window, document);


        (function (window, document, undefined) {

            'use strict';

            // Feature test
            if (!('localStorage' in window)) return;

            // Get our newly insert toggle
            var nightMode = document.querySelector('#night-mode');
            if (!nightMode) return;

            // When clicked, toggle night mode on or off
            nightMode.addEventListener('click', function (event) {
                event.preventDefault();
                document.documentElement.classList.toggle('dark');
                if (document.documentElement.classList.contains('dark')) {
                    localStorage.setItem('gmtNightMode', true);
                    return;
                }
                localStorage.removeItem('gmtNightMode');
            }, false);

        })(window, document);
    </script>-->

    <!-- Scripts
    ================================================== -->
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
  </body>
</html>

templates/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="{% static 'assets/images/favicon.png' %}"
      rel="icon"
      type="image/png"
    />
    <title>Sign Up - Social Book</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}" />
  </head>

  <body class="bg-gray-100">
    <div id="wrapper" class="flex flex-col justify-between h-screen">
      <!-- header-->
      <div class="bg-white py-4 shadow dark:bg-gray-800">
        <div class="max-w-6xl mx-auto">
          <div class="flex items-center lg:justify-between justify-around">
            <a href="trending.html">
              <b><h1 style="font-size: 1.5rem">Social Book</h1></b>
            </a>

            <div
              class="capitalize flex font-semibold hidden lg:block my-2 space-x-3 text-center text-sm"
            >
              <a
                href="{% url 'core:signin' %}"
                class="bg-pink-500 pink-500 px-6 py-3 rounded-md shadow text-white"
                >Login</a
              >
            </div>
          </div>
        </div>
      </div>

      <!-- Content-->

      <div>
        <div
          class="lg:p-12 max-w-md max-w-xl lg:my-0 my-12 mx-auto p-6 space-y-"
        >
          <h1 class="lg:text-3xl text-xl font-semibold mb-6">Sign Up</h1>

          <div>
            <style>
              h5 {
                color: salmon;
              }
            </style>

            {% for message in messages %}
            <h5>{{message}}</h5>
            {% endfor %}
          </div>

          <form action="" method="POST">
            {% csrf_token %}

            <input
              type="text"
              placeholder="Username"
              name="username"
              class="bg-gray-200 mb-2 shadow-none dark:bg-gray-800"
              style="border: 1px solid #d3d5d8 !important"
            />
            <input
              type="email"
              name="email"
              placeholder="Email"
              class="bg-gray-200 mb-2 shadow-none dark:bg-gray-800"
              style="border: 1px solid #d3d5d8 !important"
            />
            <input
              type="password"
              name="password"
              placeholder="Password"
              class="bg-gray-200 mb-2 shadow-none dark:bg-gray-800"
              style="border: 1px solid #d3d5d8 !important"
            />
            <input
              type="password"
              name="password2"
              placeholder="Confirm Password"
              class="bg-gray-200 mb-2 shadow-none dark:bg-gray-800"
              style="border: 1px solid #d3d5d8 !important"
            />
            {% comment %}
            <div class="flex justify-start my-4 space-x-1">
              <div class="checkbox">
                <input type="checkbox" id="chekcbox1" checked />
                <label for="chekcbox1"
                  ><span class="checkbox-icon"></span> I Agree</label
                >
              </div>
              <a href="#"> Terms and Conditions</a>
            </div>
            {% endcomment %}
            <button
              type="submit"
              class="bg-gradient-to-br from-pink-500 py-3 rounded-md text-white text-xl to-red-400 w-full"
            >
              Sign Up
            </button>
            <div class="text-center mt-5 space-x-2">
              <p class="text-base">
                Do you have an account?
                <a href="{% url 'core:signin' %}"> Login </a>
              </p>
            </div>
          </form>
        </div>
      </div>

      <!-- Footer -->

      <div class="lg:mb-5 py-3 uk-link-reset">
        <div
          class="flex flex-col items-center justify-between lg:flex-row max-w-6xl mx-auto lg:space-y-0 space-y-3"
        >
          <div class="flex space-x-2 text-gray-700 uppercase">
            <a href="#"> About</a>
            <a href="#"> Help</a>
            <a href="#"> Terms</a>
            <a href="#"> Privacy</a>
          </div>
          <p class="capitalize">© copyright 2020 by socol</p>
        </div>
      </div>
    </div>

    <!--<script>

        (function (window, document, undefined) {
            'use strict';
            if (!('localStorage' in window)) return;
            var nightMode = localStorage.getItem('gmtNightMode');
            if (nightMode) {
                document.documentElement.className += ' dark';
            }
        })(window, document);


        (function (window, document, undefined) {

            'use strict';

            // Feature test
            if (!('localStorage' in window)) return;

            // Get our newly insert toggle
            var nightMode = document.querySelector('#night-mode');
            if (!nightMode) return;

            // When clicked, toggle night mode on or off
            nightMode.addEventListener('click', function (event) {
                event.preventDefault();
                document.documentElement.classList.toggle('dark');
                if (document.documentElement.classList.contains('dark')) {
                    localStorage.setItem('gmtNightMode', true);
                    return;
                }
                localStorage.removeItem('gmtNightMode');
            }, false);

        })(window, document);
    </script>-->

    <!-- Scripts
    ================================================== -->
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
  </body>
</html>

templates/update_profile.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Dependent Dropdown in Django</title>
  </head>
  <body>
    <h2>Person Form</h2>

    <div>
      <style>
        h5 {
          color: green;
        }
      </style>

      {% for message in messages %}
      <h5>{{message}}</h5>
      {% endfor %}
    </div>
    <form
      method="post"
      id="personForm"
      data-cities-url="{% url 'core:ajax_load_cities' %}"
    >
      {% csrf_token %} {{ form.as_p }}
      <input type="submit" value="Submit" />
    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
      $('#id_country').change(function () {
        const url = $('#personForm').attr('data-cities-url'); // get the url of the `load_cities` view
        const countryId = $(this).val(); // get the selected country ID from the HTML input

        $.ajax({
          // initialize an AJAX request
          url: url, // set the url of the request (= /persons/ajax/load-cities/ )
          data: {
            country_id: countryId, // add the country id to the GET parameters
          },
          success: function (data) {
            // `data` is the return of the `load_cities` view function
            $('#id_city').html(data); // replace the contents of the city input with the data that came from the server
            /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
          },
        });
      });
    </script>
  </body>
</html>